"""empty message

Revision ID: 058e7609da8c
Revises: 
Create Date: 2022-01-26 16:18:52.046733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058e7609da8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('short_url', sa.String(length=8), nullable=False),
    sa.Column('last_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_urls')
    # ### end Alembic commands ###
